sudo: false
language: go
go:
  - 1.7
script:
  - make test vet
before_deploy:
  - ./scripts/build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: 
    secure: $GITHUB_TOKEN
  file_glob: true
  file: 'pkg/*.zip'
  on:
    all_branches: true
    tags: true
